# Generated by Django 2.2.4 on 2019-09-15 09:28

import datetime
from django.utils import timezone
from django.db import migrations, models

#MIGRATE FUNCTIONS
def load_composers(apps, schema_editor):
    Composer = apps.get_model('credo', 'Composer')

    c1 = Composer(id=0, name='John Doe', created_at=timezone.now(),
                    updated_at=timezone.now())
    c1.save()

    time = timezone.now() - datetime.timedelta(days=1)
    c2 = Composer(id=1, name='Jane Doe', created_at=time, updated_at=time)
    c2.save()

    time -= datetime.timedelta(days=2)
    c3 = Composer(id=2, name='Jason Hopper', created_at=time, updated_at=time)
    c3.save()

def load_songs(apps, schema_editor):
    Song = apps.get_model('credo', 'Song')
    Composer = apps.get_model('credo', 'Composer')

    composer = Composer.objects.get(id=0)
    s1 = Song(id=0, name='John Song 1', composer=composer,
        created_at=timezone.now(), updated_at = timezone.now())
    s1.save()

    time = timezone.now() - datetime.timedelta(days=1)
    s2 = Song(id=1, name='John Song 2', composer=composer, created_at=time,
              updated_at=time)
    s2.save()

    time -= datetime.timedelta(days=1)
    composer = Composer.objects.get(id=1)
    s3 = Song(id=2, name='Jane Song 1', composer=composer, created_at=time,
            updated_at=time)
    s3.save()

    time -= datetime.timedelta(days=2)
    composer = Composer.objects.get(id=2)
    s4 = Song(id=3, name='Jason Song 1', composer=composer, created_at=time,
            updated_at=time)
    s4.save()

#ROLLBACK FUNCTIONS
def delete_composers(apps, schema_editor):
    Composer = apps.get_model('credo', 'Composer')
    Composer.objects.all().delete()

def delete_songs(apps, schema_editor):
    Song = apps.get_model('credo', 'Song')
    Song.objects.all().delete()




class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_composers, delete_composers),
        migrations.RunPython(load_songs, delete_songs),
    ]
