# Generated by Django 2.2.4 on 2019-09-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='edition',
        ),
        migrations.AddField(
            model_name='comment',
            name='revision',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='credo.Revision'),
            preserve_default=False,
        ),
    ]
