# Generated by Django 2.2.4 on 2019-08-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='editions',
            field=models.ManyToManyField(to='credo.Edition'),
        ),
        migrations.DeleteModel(
            name='EditionRevision',
        ),
    ]
