# Generated by Django 2.2.4 on 2019-09-03 09:56
import datetime
from django.utils import timezone
from django.db import migrations, models

#MIGRATE FUNCTIONS
def load_composers(apps, schema_editor):
    Composer = apps.get_model('credo', 'Composer')

    c1 = Composer(id=0, name='John Doe', created_at=timezone.now(), updated_at=timezone.now())
    c1.save()

    time = timezone.now() - datetime.timedelta(days=1)
    c2 = Composer(id=1, name='Jane Doe', created_at=time, updated_at=time)
    c2.save()

    time -= datetime.timedelta(days=2)
    c3 = Composer(id=2, name='Jason Hopper', created_at=time, updated_at=time)
    c3.save()

#ROLLBACK FUNCTIONS
def delete_composers(apps, schema_editor):
    Composer = apps.get_model('credo', 'Composer')
    Composer.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0002_auto_20190828_1559'),
    ]

    operations = [
            migrations.RunPython(load_composers, delete_composers),
    ]
