# Generated by Django 2.2.4 on 2019-09-03 06:59
from django.utils import timezone
from django.db import migrations, models

#MIGRATE FUNCTIONS
def load_composers(apps, schema_editor):
    Composer = apps.get_model('credo', 'Composer')

    c1 = Composer(id=0, name='John Doe', created_at=timezone.now())
    c1.save()

    time = timezone.now() - datetime.timedelta(days=1)
    c2 = Composer(id=1, name='Jane Doe', created_at=time)
    c2.save()

    time -= datetime.timedelta(days=2)
    c3 = Composer(id=2, name='Jason Hopper', created_at=time)
    c3.save()

#ROLLBACK FUNCTIONS
def delete_composers(apps, schema_editor):
    Composer = apps.get_model('credo', 'Composer')
    Composer.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0001_initial'),
    ]

#The runPython method will use the first call when migrating to the DB.
#The second callback is used if you are rolling back
    operations = [
        migrations.runPython(load_composers, delete_composers),
    ]
