# Generated by Django 2.2.4 on 2019-10-14 08:19

from django.db import migrations


def update_revisions(apps, schema_editor):
    Revision = apps.get_model('credo', 'Revision')

    craig_revisions = Revision.objects.filter(editions__name='Christmas JS')
    luke_revisions = Revision.objects.filter(editions__name='Python Play')
    joel_revisions = Revision.objects.filter(editions__name='Green Edition')
    alex_revisions = Revision.objects.filter(
        editions__name='Congruent Edition'
    )

    idx = 1
    for r in craig_revisions:
        r.name = f'Christmas JS Revision {idx}'
        r.save()
        idx += 1

    idx = 1
    for r in luke_revisions:
        r.name = f'Python Play Revision {idx}'
        r.save()
        idx += 1

    idx = 1
    for r in joel_revisions:
        r.name = f'Green Edition Revision {idx}'
        r.save()
        idx += 1

    idx = 1
    for r in alex_revisions:
        r.name = f'Congruent Edition Revision {idx}'
        r.save()
        idx += 1


def rollback_revisions(apps, schema_editor):
    Revision = apps.get_model('credo', 'Revision')

    craig_revisions = Revision.objects.filter(editions__name='Christmas JS')
    luke_revisions = Revision.objects.filter(editions__name='Python Play')
    joel_revisions = Revision.objects.filter(editions__name='Green Edition')
    alex_revisions = Revision.objects.filter(editions__name='Congruent Edition')

    for r in craig_revisions:
        r.name = None
        r.save()

    for r in luke_revisions:
        r.name = None
        r.save()

    for r in joel_revisions:
        r.name = None
        r.save()

    for r in alex_revisions:
        r.name = None
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0003_revision_name'),
    ]

    operations = [
        migrations.RunPython(update_revisions, rollback_revisions),
    ]
