# Generated by Django 2.2.4 on 2019-10-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0004_update_seed_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
