# Generated by Django 2.2.4 on 2019-10-15 02:14

from django.db import migrations


def update_revisions(apps, schema_editor):
    Revision = apps.get_model('credo', 'Revision')

    revisions = Revision.objects.all()

    for r in revisions:
        r.resolved = True
        r.save()


def rollback_revisions(apps, schema_editor):
    Revision = apps.get_model('credo', 'Revision')

    revisions = Revision.objects.all()

    for r in revisions:
        r.resolved = False
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0005_revision_resolved'),
    ]

    operations = [
        migrations.RunPython(update_revisions, rollback_revisions),
    ]
