# Generated by Django 2.2.4 on 2019-10-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0006_resolve_existing_revisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='resolved',
        ),
        migrations.AddField(
            model_name='mei',
            name='normalised',
            field=models.BooleanField(default=True),
        ),
    ]
