version: "3"
services:
  db:
    image: "postgres:11.5-alpine"
    container_name: "credo_postgres"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ../.env


volumes:
  data:
